# Generated by Django 4.1.7 on 2023-04-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('fields', models.JSONField(verbose_name='Поля')),
                ('editable', models.BooleanField(default=True, verbose_name='Возможно редактирование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_n', models.SmallIntegerField(verbose_name='Курс')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reports.faculty', verbose_name='Факультет')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TablePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.JSONField(verbose_name='Данные')),
                ('group_n', models.SmallIntegerField(verbose_name='Группа')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='tables.table', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Часть таблицы',
                'verbose_name_plural': 'Части таблиц',
                'ordering': ('group_n',),
            },
        ),
    ]
