# Generated by Django 4.0 on 2022-01-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_changesattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpair',
            name='work_out_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отработки'),
        ),
        migrations.AlterField(
            model_name='pairsschedule',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.lecturesschedule', verbose_name='Лекция'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_add_lecture_url',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Добавляет ссылки на лекции'),
        ),
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID Вконтакте'),
        ),
    ]
