# Generated by Django 4.0 on 2022-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_missingpair_work_out_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesschedule',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Ссылка была разослана'),
        ),
    ]
