# Generated by Django 4.0 on 2022-01-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_lecturesschedule_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesschedule',
            name='stud_add_lec',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.student', verbose_name='Кто добавил лекцию'),
        ),
    ]
