# Generated by Django 4.0 on 2022-08-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_lecturesschedule_lecture_url'),
        ('reports', '0006_alter_lecturesschedule_lecture_url'),
    ]

    operations = [
    ]
