# Generated by Django 4.0 on 2022-01-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0002_alter_changesattendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeansUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_n', models.CharField(max_length=20, null=True, verbose_name='Курсы')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.faculty', verbose_name='Факультет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнение Декан',
                'verbose_name_plural': 'Дополнения Деканы',
                'ordering': ['faculty', 'courses_n'],
            },
        ),
    ]
