# Generated by Django 4.0 on 2022-01-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_changesattendance_options_and_more'),
        ('usersext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deansuser',
            name='courses_n',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='deansuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.faculty', verbose_name='Факультет'),
        ),
    ]
